version: '3.8'

services:

  # Reverse-proxy service. This should be the only service with
  # publicly-exposed ports.
  proxy:
    build:
      dockerfile: dockerfiles/Dockerfile
      context: .
      target: proxy
    volumes:
      - ./config/local/nginx:/etc/nginx
    networks:
      - mallard
