# Config file for local MALLARD deployments. This is used by the default
# docker-compose configuration.

# Common SQL configuration.
_sql_config: &sql_config
  config:
    endpoint_url: "mysql+aiomysql://root:TnrHYavLF7WF38@metadata-store/mallard_meta?charset=utf8mb4"

# Base URL for the API that the frontend will use to communicate
# with the backend.
api_base_url: "https://localhost:8081/api/v1"
# Base URL of the transcoder service.
transcoder_base_url: http://transcoder:8000

backends:
  # Configuration for the object store backend.
  object_store:
    type: mallard.gateway.backends.objects.s3_object_store.S3ObjectStore
    config:
      region_name: us-east-1
      access_key: HFgwH5U5RNaAbe
      access_key_id: minio_user_51c173
      endpoint_url: http://object-store:9000

  # Configuration for the metadata store backend.
  artifact_metadata_store:
    type: mallard.gateway.backends.metadata.sql.SqlArtifactMetadataStore
    <<: *sql_config

  image_metadata_store:
    type: mallard.gateway.backends.metadata.sql.SqlImageMetadataStore
    <<: *sql_config

  video_metadata_store:
    type: mallard.gateway.backends.metadata.sql.SqlVideoMetadataStore
    <<: *sql_config

security:
  # Enable authentication.
  enable_auth: true

  # Origins to allow API requests from.
  api_origins:
    - "https://127.0.0.1:8081"
    - "https://localhost:8081"
