# Config file for local MALLARD deployments. This is used by the default
# docker-compose configuration.

# Base URL for the API that the frontend will use to communicate
# with the backend.
api_base_url: "http://localhost:8081/api/v1"

backends:
  # Configuration for the object store backend.
  object_store:
    type: mallard.gateway.backends.objects.s3_object_store.S3ObjectStore
    config:
      region_name: us-east-1
      access_key: HFgwH5U5RNaAbe
      access_key_id: minio_user_51c173
      endpoint_url: http://object-store:9000

  # Configuration for the metadata store backend.
  metadata_store:
    type: mallard.gateway.backends.metadata.sql.SqlImageMetadataStore
    config:
      endpoint_url: "mysql+aiomysql://root:TnrHYavLF7WF38@metadata-store/mallard_meta?charset=utf8mb4"

security:
  # Disable authentication.
  enable_auth: false

  # Origins to allow API requests from.
  api_origins:
    - "http://127.0.0.1:8081"
    - "http://localhost:8081"
