transcoder:
  # Base URL of the transcoder service.
  base_url: http://transcoder:8000
  # The maximum number of concurrent transcoding processes to run.
  max_num_processes: 2

security:
  fief:
    # Default to no Fief configuration.
    base_url: ""
    client_id: ""
    verify_ssl: true
