# Example config file for MALLARD. The real config file is located in
# `~/.config/mallard/config.yaml`.

# Common SQL configuration.
_sql_config: &sql_config
  config:
    endpoint_url: "mysql+aiomysql://root:password@localhost/mallard_meta?charset=utf8mb4"

backends:
  # Configuration for the object store backend.
  object_store:
    type: mallard.gateway.backends.objects.s3_object_store.S3ObjectStore
    config:
      region_name: us-east-1
      access_key: minioadmin
      access_key_id: minioadmin
      endpoint_url: http://127.0.0.1:9000

  # Configuration for the metadata store backend.
  image_metadata_store:
    type: mallard.gateway.backends.metadata.sql.SqlImageMetadataStore
    << : *sql_config

  video_metadata_store:
    type: mallard.gateway.backends.metadata.sql.SqlVideoMetadataStore
    << : *sql_config


# URL endpoint we use for authentication.
auth_url: https://example.com/auth/
# Base URL of the transcoder service.
transcoder_base_url: http://transcoder:8000
