env:
  browser: true
  es2021: true
extends:
  - google
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  no-unused-vars: "off"
  "@typescript-eslint/no-unused-vars": [
    "error",
    {
      "argsIgnorePattern": "^_",
      # It seems to have trouble with these specific
      # imports, so we ignore them manually.
      "varsIgnorePattern": "^property$|^query$|^isEqual$|^_"
    }
  ]
  new-cap:
    - error
    - capIsNewExceptions:
      - Set
      - Map
      - UavImageMetadataFromJSON
      - UavImageMetadataToJSON
ignorePatterns:
  # Generated type files.
  - "*.d.ts"
